import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import cookie from '@fastify/cookie';
import csrfProtection from '@fastify/csrf-protection';
import rateLimit from '@fastify/rate-limit';
import session from '@fastify/session';
import websocket from '@fastify/websocket';
import Fastify, { type FastifyInstance } from 'fastify';
import { SqliteSessionStore } from './db/sessionsRepo.js';
import { authRoutes } from './routes/auth.routes.js';
import { captureRoutes } from './routes/capture.routes.js';
import { cdpRoutes } from './routes/cdp.routes.js';
import { configRoutes } from './routes/config.routes.js';
import { disclaimerRoutes } from './routes/disclaimer.routes.js';
import { logsRoutes } from './routes/logs.routes.js';
import { mfaRoutes } from './routes/mfa.routes.js';
import { storageRoutes } from './routes/storage.routes.js';
import { telegramRoutes } from './routes/telegram.routes.js';
import { wsRoutes } from './routes/ws.routes.js';

const SESSION_SECRET = process.env.EVERYFRAME_SESSION_SECRET ?? 'dev-only-secret-change-me-32-chars-min';
const IS_PROD = process.env.NODE_ENV === 'production';

if (SESSION_SECRET.length < 32) {
  throw new Error('EVERYFRAME_SESSION_SECRET must be at least 32 characters.');
}
if (IS_PROD && SESSION_SECRET.startsWith('dev-only-secret')) {
  throw new Error('Set EVERYFRAME_SESSION_SECRET before running in production.');
}

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Local-dev HTTPS, opt-in via EVERYFRAME_HTTPS=true (never auto-detected, so `npm test`'s
 * buildApp() calls stay unaffected even if cert files happen to exist on disk). Points at a
 * self-signed cert generated by `npm run generate-cert` - see scripts/generate-dev-cert.mjs.
 * Not a substitute for a real cert/reverse-proxy TLS termination in production.
 */
function loadHttpsOptions(): { cert: Buffer; key: Buffer } | undefined {
  if (process.env.EVERYFRAME_HTTPS !== 'true' || process.env.NODE_ENV === 'test') return undefined;
  const certPath = process.env.EVERYFRAME_TLS_CERT_PATH ?? join(__dirname, '..', 'certs', 'localhost-cert.pem');
  const keyPath = process.env.EVERYFRAME_TLS_KEY_PATH ?? join(__dirname, '..', 'certs', 'localhost-key.pem');
  try {
    return { cert: readFileSync(certPath), key: readFileSync(keyPath) };
  } catch (err) {
    throw new Error(
      `EVERYFRAME_HTTPS=true but the cert/key couldn't be read (${certPath}, ${keyPath}). Run "npm run generate-cert -w packages/server" first. Original error: ${(err as Error).message}`,
    );
  }
}

/** Builds a fully-configured Fastify instance without binding a port - used by both server.ts and tests. */
export async function buildApp(): Promise<FastifyInstance> {
  const httpsOptions = loadHttpsOptions();
  const logger = process.env.NODE_ENV !== 'test';
  // Two distinct calls (rather than one with `https: httpsOptions | undefined`) so TypeScript
  // can resolve Fastify's http-vs-https overloads unambiguously; the cast reconciles the two
  // branches' differing server generics down to the plain FastifyInstance used everywhere else.
  const app = (httpsOptions ? Fastify({ logger, https: httpsOptions }) : Fastify({ logger })) as FastifyInstance;

  await app.register(rateLimit, {
    max: process.env.NODE_ENV === 'test' ? 100_000 : 100,
    timeWindow: '1 minute',
  });
  await app.register(cookie);
  await app.register(session, {
    secret: SESSION_SECRET,
    cookieName: 'sid',
    store: new SqliteSessionStore(),
    cookie: {
      httpOnly: true,
      secure: IS_PROD,
      sameSite: 'lax',
      maxAge: 1000 * 60 * 60 * 24, // 24h
    },
  });
  await app.register(csrfProtection, { sessionPlugin: '@fastify/session' });
  await app.register(websocket);

  app.get('/api/health', async () => ({ status: 'ok' }));

  await app.register(authRoutes);
  await app.register(mfaRoutes);
  await app.register(cdpRoutes);
  await app.register(configRoutes);
  await app.register(telegramRoutes);
  await app.register(captureRoutes);
  await app.register(storageRoutes);
  await app.register(logsRoutes);
  await app.register(disclaimerRoutes);
  await app.register(wsRoutes);

  return app;
}
